In [1]:
import pandas as pd

data = pd.read_csv('./data/collected_experimental_data.csv')

In [2]:
# Parameter counts

print(data[['Model', 'Param Count']].drop_duplicates())

  Model  Param Count
0  IRNN         4003
1   STT      3275971
2  LTCN         7107

In [8]:
acc_mcc = data[['Experiment', 'Model', 'Test Accuracy', 'MCC']]

acc_mcc.loc[acc_mcc['Experiment'].isin(['config_tgtsym_bivi.yml', 'config_tgtsym_atnf.yml', 'config_tgtsym_vtak.yml', 'config_tgtsym_cycc.yml'])].sort_values(by='Experiment')

                Experiment Model  Test Accuracy       MCC
12  config_tgtsym_atnf.yml  IRNN       0.464970  0.040469
13  config_tgtsym_atnf.yml   STT       0.378224  0.025978
14  config_tgtsym_atnf.yml  LTCN       0.519685  0.000000
24  config_tgtsym_bivi.yml  IRNN       0.487903  0.041091
25  config_tgtsym_bivi.yml   STT       0.354043 -0.006121
26  config_tgtsym_bivi.yml  LTCN       0.503937  0.000000
3   config_tgtsym_cycc.yml  IRNN       0.471774 -0.000960
4   config_tgtsym_cycc.yml   STT       0.409102 -0.006718
5   config_tgtsym_cycc.yml  LTCN       0.535433  0.000000
6   config_tgtsym_vtak.yml  IRNN       0.291583  0.033260
7   config_tgtsym_vtak.yml   STT       0.275050 -0.081573
8   config_tgtsym_vtak.yml  LTCN       0.496063  0.000000

In [4]:
acc_mcc = data[['Experiment', 'Model', 'Test Accuracy', 'MCC']]

acc_mcc.loc[acc_mcc['Experiment'].isin(['config_target_split_01.yml', 'config_target_split_25.yml', 'config_target_split_50.yml', 'config_target_split_75.yml', 'config_target_split_99.yml'])]

                    Experiment Model  Test Accuracy       MCC
0   config_target_split_01.yml  IRNN       0.094254  0.001528
1   config_target_split_01.yml   STT       0.377728 -0.050258
2   config_target_split_01.yml  LTCN       0.409449  0.000000
15  config_target_split_75.yml  IRNN       0.433216  0.002869
16  config_target_split_75.yml   STT       0.377604  0.019294
17  config_target_split_75.yml  LTCN       0.503937  0.000000
21  config_target_split_50.yml  IRNN       0.487903  0.035975
22  config_target_split_50.yml   STT       0.385541  0.031715
23  config_target_split_50.yml  LTCN       0.503937  0.000000
27  config_target_split_25.yml  IRNN       0.512097  0.069196
28  config_target_split_25.yml   STT       0.386037 -0.038507
29  config_target_split_25.yml  LTCN       0.488189  0.030832
30  config_target_split_99.yml  IRNN       0.495968 -0.010933
31  config_target_split_99.yml   STT       0.385541 -0.010786
32  config_target_split_99.yml  LTCN       0.503937  0.000000

In [5]:
acc_mcc.loc[acc_mcc['Experiment'].isin(['config_target_split_01.yml', 'config_target_split_25.yml', 'config_target_split_50.yml', 'config_target_split_75.yml', 'config_target_split_99.yml'])].to_numpy()

array([['config_target_split_01.yml', 'IRNN', 0.0942540322580645,
        0.0015282375563635],
       ['config_target_split_01.yml', 'STT', 0.3777281746031746,
        -0.0502575211858512],
       ['config_target_split_01.yml', 'LTCN', 0.4094488188976378, 0.0],
       ['config_target_split_75.yml', 'IRNN', 0.4332157258064516,
        0.0028686340368981],
       ['config_target_split_75.yml', 'STT', 0.3776041666666666,
        0.0192935616207909],
       ['config_target_split_75.yml', 'LTCN', 0.5039370078740157, 0.0],
       ['config_target_split_50.yml', 'IRNN', 0.4879032258064516,
        0.0359747003889467],
       ['config_target_split_50.yml', 'STT', 0.3855406746031746,
        0.0317149103099963],
       ['config_target_split_50.yml', 'LTCN', 0.5039370078740157, 0.0],
       ['config_target_split_25.yml', 'IRNN', 0.5120967741935484,
        0.0691963423974115],
       ['config_target_split_25.yml', 'STT', 0.3860367063492063,
        -0.0385071148859973],
       ['config_target_split_25.yml', 'LTCN', 0.4881889763779528,
        0.0308324650211252],
       ['config_target_split_99.yml', 'IRNN', 0.4959677419354839,
        -0.0109327938583024],
       ['config_target_split_99.yml', 'STT', 0.3855406746031746,
        -0.0107862596899669],
       ['config_target_split_99.yml', 'LTCN', 0.5039370078740157, 0.0]],
      dtype=object)

In [6]:
results = data[['Experiment', 'Model', 'Pretrain Average Epoch time', 'Pretrain Average Train time', 'Pretrain Average Validate time', 'Pretrain Split', 'Average Epoch time', 'Average Train time', 'Average Validate time']]

results.loc[results['Experiment'] == 'config_tgtsym_bivi.yml'][['Model', 'Pretrain Average Epoch time', 'Pretrain Average Train time', 'Pretrain Average Validate time', 'Pretrain Split', 'Average Epoch time', 'Average Train time', 'Average Validate time']]

,Model,Pretrain Average Epoch time,Pretrain Average Train time,Pretrain Average Validate time,Pretrain Split,Average Epoch time,Average Train time,Average Validate time
24,IRNN,0.091246,0.088223,0.239817,0.80,0.021841,0.018716,0.058889
25,STT,0.904031,0.894946,2.173719,0.80,0.188575,0.179529,0.532234
26,LTCN,2.266351,2.229288,2.184783,0.59,0.480549,0.444504,1.476724

In [7]:

times = results.loc[results['Experiment'] == 'config_tgtsym_bivi.yml'][['Pretrain Average Epoch time', 'Pretrain Average Train time', 'Pretrain Average Validate time', 'Pretrain Split', 'Average Epoch time', 'Average Train time', 'Average Validate time']]

numpy_val = times.to_numpy()

averages = numpy_val[:, :3] * numpy_val[:, 3] + (1 - numpy_val[:, 3]) * numpy_val[:, 4:]

averages

array([[0.0773649 , 0.07432165, 0.16563669],
       [0.76093988, 0.75186297, 1.5007099 ],
       [1.90919073, 1.87233112, 1.89447865]])