In [3]:
import pandas as pd

data = pd.read_csv('./data/collected_experimental_data.csv')

In [ ]:
# Parameter counts

print(data[['Model', 'Param Count']].drop_duplicates())

         Model  Param Count
0          rnn         4003
1  transformer      3275971
2          lnn         7107

In [ ]:
acc_mcc = data[['Experiment', 'Model', 'Test Accuracy', 'MCC']]

acc_mcc.loc[acc_mcc['Experiment'].isin(['config_tgtsym_bivi.yml', 'config_tgtsym_atnf.yml', 'config_tgtsym_vtak.yml', 'config_tgtsym_cycc.yml'])]

                Experiment        Model  Test Accuracy       MCC
3   config_tgtsym_bivi.yml          rnn       0.511341  0.076816
4   config_tgtsym_bivi.yml  transformer       0.432664  0.081534
5   config_tgtsym_bivi.yml          lnn       0.503937  0.000000
6   config_tgtsym_vtak.yml          rnn       0.276462  0.045967
7   config_tgtsym_vtak.yml  transformer       0.322545 -0.066805
8   config_tgtsym_vtak.yml          lnn       0.496063  0.000000
15  config_tgtsym_atnf.yml          rnn       0.377520  0.083746
16  config_tgtsym_atnf.yml  transformer       0.369544  0.044597
17  config_tgtsym_atnf.yml          lnn       0.519685  0.000000
22  config_tgtsym_cycc.yml          rnn       0.542843  0.078236
23  config_tgtsym_cycc.yml  transformer       0.433036  0.057799
24  config_tgtsym_cycc.yml          lnn       0.535433  0.000000

In [11]:
acc_mcc = data[['Experiment', 'Model', 'Test Accuracy', 'MCC']]

acc_mcc.loc[acc_mcc['Experiment'].isin(['config_target_split_01.yml', 'config_target_split_25.yml', 'config_target_split_50.yml', 'config_target_split_75.yml', 'config_target_split_99.yml'])]

                    Experiment        Model  Test Accuracy       MCC
0   config_target_split_50.yml          rnn       0.503528  0.064383
1   config_target_split_50.yml  transformer       0.472470  0.065455
2   config_target_split_50.yml          lnn       0.503937  0.000000
9   config_target_split_75.yml          rnn       0.402218 -0.053647
10  config_target_split_75.yml  transformer       0.416915  0.075041
11  config_target_split_75.yml          lnn       0.503937  0.000000
18  config_target_split_01.yml          rnn       0.086442 -0.026915
19  config_target_split_01.yml  transformer       0.464658  0.043204
20  config_target_split_01.yml          lnn       0.409449  0.000000
25  config_target_split_99.yml          rnn       0.527974  0.099653
26  config_target_split_99.yml  transformer       0.401290  0.050552
27  config_target_split_99.yml          lnn       0.503937  0.000000
31  config_target_split_25.yml          rnn       0.527218  0.099687
32  config_target_split_25.yml  transformer       0.440600 -0.004303
33  config_target_split_25.yml          lnn       0.488189  0.030832

In [24]:
results = data[['Experiment', 'Model', 'Pretrain Average Epoch time', 'Pretrain Average Train time', 'Pretrain Average Validate time', 'Pretrain Split', 'Average Epoch time', 'Average Train time', 'Average Validate time']]

results.loc[results['Experiment'] == 'config_tgtsym_bivi.yml'][['Model', 'Pretrain Average Epoch time', 'Pretrain Average Train time', 'Pretrain Average Validate time', 'Pretrain Split', 'Average Epoch time', 'Average Train time', 'Average Validate time']]

,Model,Pretrain Average Epoch time,Pretrain Average Train time,Pretrain Average Validate time,Pretrain Split,Average Epoch time,Average Train time,Average Validate time
3,rnn,0.136406,0.132401,0.315976,0.80,0.030751,0.026757,0.074846
4,transformer,0.551723,0.544450,1.732548,0.80,0.116397,0.109172,0.423073
5,lnn,4.021306,3.956087,3.843853,0.59,0.823026,0.762381,2.483775

In [25]:

times = results.loc[results['Experiment'] == 'config_tgtsym_bivi.yml'][['Pretrain Average Epoch time', 'Pretrain Average Train time', 'Pretrain Average Validate time', 'Pretrain Split', 'Average Epoch time', 'Average Train time', 'Average Validate time']]

numpy_val = times.to_numpy()

averages = numpy_val[:, :3] * numpy_val[:, 3] + (1 - numpy_val[:, 3]) * numpy_val[:, 4:]

averages

array([[0.11527493, 0.11127259, 0.21711292],
       [0.46465782, 0.45739424, 1.19566299],
       [3.38164994, 3.31734618, 3.2862213 ]])